# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "yN89z0wbBdZioY3TgRUgG9kECgYhd985W4K/vHmY6ea3qF7T+13sCD/jZM2zUDcgyyBsxLZv/rKKybuO/k74yJCdDVa1S46U52Okj1C4r12ozCY5umy6D8SFuE2wwB2zfIE2hPpb8oAh2KlVV8Fq1cwBI3mNTrsZ3+V0pK1TEF3iT3TbB5IJC3hyga0V7a1chR/wjj2NXD6wuquk1USx/1bOqh8Ym0c27YvSbXk8aAd+QZYX2jTZRUjfnTAPTfrOzUSY6EbT/otjtYum5YhxhD0TEo92fy8YAosjaScsoKcaKhib0FuDEilGo/mZXdb/INzqx6CisLxrP05Z2lvwD2FFHj/C6dDYiYcpOwBkt57IGDJTb0yqVN3whMPW+b8hqKmOeUx0LI7wphxm00VSklpiPR9ze0Si1WQqIXsai68ctyHCOqFzxPsrB9GuSc7au3O4xGI2HG7Qm9mqaVMSAOnN8pmPceS6VrxagG8z+6wsa0gbXVvhA55wFmI+aMNAHaBxFwYUZWzYvzRwHFWL7cs6rN3ODVrfbRLqy5lQtGbiiPmOQqou370j6KxF+6UBd1p/bdsUQW8tIVjNQbnhoTnW3qAo9W1O6D/stkfQ/Hou6V6frkdjoE+pbfY08Uw5ZHXNzylHhVixE9W8xFXyhZ4EPlkD9yxLOhUl85nrf7Q="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
